// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-0V_UiXREGAWi4g20Q_Xpz8nGnT_YtY',
    appId: '1:970083390580:web:9914df066fdbbf14c46d21',
    messagingSenderId: '970083390580',
    projectId: 'lms-chatbot-7fbd0',
    authDomain: 'lms-chatbot-7fbd0.firebaseapp.com',
    storageBucket: 'lms-chatbot-7fbd0.firebasestorage.app',
    measurementId: 'G-QLSZ75XWBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfftcxWYKwvq90phkBnHepSndMAVC2Onw',
    appId: '1:970083390580:android:de97e398e101abc7c46d21',
    messagingSenderId: '970083390580',
    projectId: 'lms-chatbot-7fbd0',
    storageBucket: 'lms-chatbot-7fbd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjNi898wDJyrL76V190le7KsyBaGWDCzk',
    appId: '1:970083390580:ios:c37d7987d4dfe855c46d21',
    messagingSenderId: '970083390580',
    projectId: 'lms-chatbot-7fbd0',
    storageBucket: 'lms-chatbot-7fbd0.firebasestorage.app',
    iosBundleId: 'com.example.lmsChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjNi898wDJyrL76V190le7KsyBaGWDCzk',
    appId: '1:970083390580:ios:c37d7987d4dfe855c46d21',
    messagingSenderId: '970083390580',
    projectId: 'lms-chatbot-7fbd0',
    storageBucket: 'lms-chatbot-7fbd0.firebasestorage.app',
    iosBundleId: 'com.example.lmsChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh-0V_UiXREGAWi4g20Q_Xpz8nGnT_YtY',
    appId: '1:970083390580:web:d713527dd3d253e5c46d21',
    messagingSenderId: '970083390580',
    projectId: 'lms-chatbot-7fbd0',
    authDomain: 'lms-chatbot-7fbd0.firebaseapp.com',
    storageBucket: 'lms-chatbot-7fbd0.firebasestorage.app',
    measurementId: 'G-DFM1LM21ML',
  );
}
